### PR TITLE
ids using snort 

### PR DESCRIPTION
**Pull request by SimranLahrani842**
fixes issue #58 
entire steps are explained in detail and are implemented by myself. Just follow the steps to achieve ids Using snort!!
It can be done in Windows and ubuntu.
I have mentioned steps in window.

### CODE REVIEW

**Comment by SimranLahrani842** [comment]
please review my pr @KTom101 , @yangc95 and @SSwiniarski

**Comment by KTom101** [comment]
@SimranLahrani842 Thank you for your submission. There are a few things that need to be addressed. 

First, the metadata that should be at the top of the file is missing. Please look in the [documentation](https://github.com/Codecademy/ugc/tree/main/documentation) folder to see the mockups of how the metadata should look. You can do this by viewing the raw files.  

Secondly, when [viewing the file](https://github.com/Codecademy/ugc/blob/9985e27bcd0c98ce4fc5ce1a389ad206689c1aba/documentation/ids.md), the structure is very unclear without the use of line breaks and spacing. Particularly in the step-by-step instructions shown in the image below:

Screenshot 2023-06-27 at 5 09 09 PM

Third, for writing a tutorial like this, it is important to add images so the reader can have a better idea of what's going on. If you're having trouble understanding what we're looking for in UGC content, please take a look at some other UGC content like the ones listed [here](https://github.com/Codecademy/ugc#what-are-community-articles). You can also look in the [content folder](https://github.com/Codecademy/ugc/tree/main/content) to view the raw files.

**Comment by SimranLahrani842** [comment]
> @SimranLahrani842 Thank you for your submission. There are a few things that need to be addressed.
> 
> First, the metadata that should be at the top of the file is missing. Please look in the [documentation](https://github.com/Codecademy/ugc/tree/main/documentation) folder to see the mockups of how the metadata should look. You can do this by viewing the raw files.
> 
> Secondly, when [viewing the file](https://github.com/Codecademy/ugc/blob/9985e27bcd0c98ce4fc5ce1a389ad206689c1aba/documentation/ids.md), the structure is very unclear without the use of line breaks and spacing. Particularly in the step-by-step instructions shown in the image below:
> 
> Screenshot 2023-06-27 at 5 09 09 PM
> Third, for writing a tutorial like this, it is important to add images so the reader can have a better idea of what's going on. If you're having trouble understanding what we're looking for in UGC content, please take a look at some other UGC content like the ones listed [here](https://github.com/Codecademy/ugc#what-are-community-articles). You can also look in the [content folder](https://github.com/Codecademy/ugc/tree/main/content) to view the raw files.

Got it mam I ll do the required changes.

**Comment by yangc95** [comment]
Just checking in @SimranLahrani842 are you still working on this?

**Comment by KTom101** [comment]
@SimranLahrani842 Closing this out due to inactivity.

**Pull request closed without merging**
